stages:
  - docker
  - test
  - publish

variables:
  CONTAINER_REGISTRY: registry.gitlab.com
  CONTAINER_IMAGE: $CONTAINER_REGISTRY/taig-github/color
  DOCKER_DRIVER: overlay2

docker:
  stage: docker
  image: docker
  services:
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CONTAINER_REGISTRY
    - docker pull $CONTAINER_IMAGE:latest || true
    - docker build --cache-from $CONTAINER_IMAGE:latest --tag $CONTAINER_IMAGE:latest --tag $CONTAINER_IMAGE:$CI_COMMIT_SHA .
    - docker push $CONTAINER_IMAGE

formatting:
  stage: test
  image: $CONTAINER_IMAGE:$CI_COMMIT_SHA
  script:
    - sbt scalafmtCheckAll

warnings:
  stage: test
  image: $CONTAINER_IMAGE:$CI_COMMIT_SHA
  script:
    - sbt -Dmode=strict test:compile

unit:
  stage: test
  image: $CONTAINER_IMAGE:$CI_COMMIT_SHA
  script:
    - sbt +test publishLocal
  artifacts:
    expire_in: 1 month
    paths:
      - coverage/

publish:
  stage: publish
  image: $CONTAINER_IMAGE:$CI_COMMIT_SHA
  only:
    - master
    - tags
  script:
    - sbt publishAndRelease
